# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false
# 1行目からclassキーワードの使用を許可する
Style/Documentation:
  Enabled: false
# 160文字以上は禁止する
Metrics/LineLength:
  Max: 160
# 50文字以上は禁止する
Metrics/BlockLength:
  Max: 50